### ISSUE TITLE
Adapter trimming

### ISSUE THREAD

**Issue by mmiladi** [paultsw/polya_analysis#1]
Hello @paultsw ,
Thanks much for providing these resources. I have question regarding the adapter trimming strategy for the DRS, specially for proper treating of nanopolish polya analysis. Which tool should be used to trim the adapters?
Thanks and best,
Milad

**Comment by paultsw** [comment]
If you just want to trim the raw current signal, you could use the output of `nanopolish polya` to do that.

If, however, you want to remove the erroneously-basecalled bases from a direct RNA sequence, that is a bit more complicated.

Offhand, there is [porechop](https://github.com/rrwick/Porechop), but it is no longer maintained and I don't think it supports RNA (though I may be wrong on this last point).

In principle, you could use the `nanopolish polya` output to trim the raw current signal and then use nanopolish's signal-to-base alignment (via `nanopolish eventalign`) to remap the signal to the bases. This might take a bit of extra work and some custom scripting to go from untrimmed fastq/fasta to trimmed fastq/fasta; unfortunately I don't know of a standalone program that does this in one pass.
