### ISSUE TITLE
Coordinates matching from fast5 and fastq data

### ISSUE THREAD

**Issue by bioinfo23** [paultsw/polya_analysis#3]
Hi ! I have performed polyA analysis as per the protocol, based on which we have polyA tails detected from fast5 files. Further if i check the coordinates for the same read in fastq file it does not match? Why is there a variation in coordinates of the polyA result and fastq file?

Thank you.
Garima

**Comment by paultsw** [comment]
Hi Garima,

My sincere apologies, this repo is no longer current (and in fact I no longer work in the bioinformatics field).

Your best bet would be to raise this issue in the official nanopolish repository:
https://github.com/jts/nanopolish
